In [1]:
import numpy as np

In [2]:
l2 = [[1,2,3],[4,5,6]]

In [3]:
l2

[[1, 2, 3], [4, 5, 6]]

In [5]:
type(l2)

list

In [6]:
arr2 = np.array(l2)

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
type(arr2)

numpy.ndarray

In [10]:
arr2.ndim

2

In [16]:
arr2.size # total elements, also called flattening

6

In [13]:
len(l2)

2

In [15]:
len(arr2)

2

In [18]:
arr2.dtype #data type of elements

dtype('int32')

In [20]:
arr2.shape # (outer elements, inner elements)

(2, 3)

In [21]:
l1 = [[1,2,3],[4,5,6.0]]

In [22]:
arr1 = np.array(l1)

In [23]:
arr1.dtype

dtype('float64')

In [27]:
arr3 = np.array([ [[1,2], [3,4], [5,6]] , [[7,8],[9,0],[1,2]] ])

In [28]:
arr3

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[7, 8],
        [9, 0],
        [1, 2]]])

In [34]:
arr3.shape # outer elements 2, inner elements 3, inner elements 2

(2, 3, 2)

In [30]:
# outer elements 2, inner elements 3, inner elements 2

In [31]:
arr3.ndim

3

In [33]:
arr3.size #2*3*2

12

In [35]:
arr3.dtype 

dtype('int32')

In [36]:
l1 = [1,2,3,4,5]

In [37]:
arr1 = np.array(l1)

In [38]:
arr1

array([1, 2, 3, 4, 5])

In [39]:
arr1.shape

(5,)

In [40]:
t1 = (5,)

In [41]:
type(t1)

tuple

In [42]:
l1

[1, 2, 3, 4, 5]

In [43]:
l1 + 10

TypeError: can only concatenate list (not "int") to list

In [44]:
l1 + l1

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [45]:
arr1

array([1, 2, 3, 4, 5])

In [46]:
arr1 + 10

array([11, 12, 13, 14, 15])

In [47]:
l1

[1, 2, 3, 4, 5]

In [48]:
np.array(l1) +10

array([11, 12, 13, 14, 15])

In [49]:
list(np.array(l1) +10)

[11, 12, 13, 14, 15]

In [50]:
arr1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [53]:
arr1

array([1, 2, 3, 4, 5])

In [51]:
arr1 // 3

array([0, 0, 1, 1, 1], dtype=int32)

In [52]:
arr1 % 2 == 0

array([False,  True, False,  True, False])

In [58]:
out = arr1 % 2 == 0

In [59]:
out.dtype

dtype('bool')

In [60]:
# arange

In [61]:
a1 = np.arange(10,20,3)

In [62]:
a1

array([10, 13, 16, 19])

In [63]:
list(range(10,20,3))

[10, 13, 16, 19]

In [64]:
range(10,20,3)

range(10, 20, 3)

In [65]:
range(2,5,0.3)

TypeError: 'float' object cannot be interpreted as an integer

In [67]:
a1 = np.arange(10,20,0.3)

In [68]:
a1

array([10. , 10.3, 10.6, 10.9, 11.2, 11.5, 11.8, 12.1, 12.4, 12.7, 13. ,
       13.3, 13.6, 13.9, 14.2, 14.5, 14.8, 15.1, 15.4, 15.7, 16. , 16.3,
       16.6, 16.9, 17.2, 17.5, 17.8, 18.1, 18.4, 18.7, 19. , 19.3, 19.6,
       19.9])

In [69]:
a1.dtype

dtype('float64')

In [70]:
np.arange(10,5,-1)

array([10,  9,  8,  7,  6])

In [73]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections 

In [74]:
np.arange('2024-03-01', '2024-03-31')

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [78]:
np.arange('2024-03-01', '2024-03-31', dtype='datetime64[D]')

array(['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04',
       '2024-03-05', '2024-03-06', '2024-03-07', '2024-03-08',
       '2024-03-09', '2024-03-10', '2024-03-11', '2024-03-12',
       '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-16',
       '2024-03-17', '2024-03-18', '2024-03-19', '2024-03-20',
       '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24',
       '2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28',
       '2024-03-29', '2024-03-30'], dtype='datetime64[D]')

In [80]:
np.arange('2024-03-01', '2024-05-31',7, dtype='datetime64[D]')

array(['2024-03-01', '2024-03-08', '2024-03-15', '2024-03-22',
       '2024-03-29', '2024-04-05', '2024-04-12', '2024-04-19',
       '2024-04-26', '2024-05-03', '2024-05-10', '2024-05-17',
       '2024-05-24'], dtype='datetime64[D]')

In [82]:
np.arange('2024-03-01', '2024-05-31',1, dtype='datetime64[M]')

array(['2024-03', '2024-04'], dtype='datetime64[M]')

In [87]:
np.arange('2024-03-01', '2024-05-31',1, dtype='datetime64[W]')

array(['2024-02-29', '2024-03-07', '2024-03-14', '2024-03-21',
       '2024-03-28', '2024-04-04', '2024-04-11', '2024-04-18',
       '2024-04-25', '2024-05-02', '2024-05-09', '2024-05-16',
       '2024-05-23'], dtype='datetime64[W]')

In [88]:
np.arange('2023-03-01', '2025-05-31',1, dtype='datetime64[M]')

array(['2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08',
       '2023-09', '2023-10', '2023-11', '2023-12', '2024-01', '2024-02',
       '2024-03', '2024-04', '2024-05', '2024-06', '2024-07', '2024-08',
       '2024-09', '2024-10', '2024-11', '2024-12', '2025-01', '2025-02',
       '2025-03', '2025-04'], dtype='datetime64[M]')

In [89]:
# random package

In [90]:
# randint

In [91]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

In [92]:
np.random.randint(10,30,(10,))

array([26, 26, 10, 26, 18, 28, 16, 14, 11, 27])

In [93]:
np.random.randint(1,9,(3,4))

array([[8, 8, 7, 1],
       [2, 6, 7, 8],
       [2, 7, 8, 8]])

In [94]:
np.random.randint(1,9,(3,4,4))

array([[[8, 1, 8, 1],
        [7, 1, 5, 2],
        [1, 8, 4, 2],
        [3, 7, 1, 8]],

       [[3, 1, 5, 3],
        [8, 3, 1, 7],
        [4, 8, 2, 2],
        [7, 7, 3, 4]],

       [[1, 5, 2, 7],
        [8, 3, 1, 7],
        [8, 4, 3, 7],
        [3, 7, 3, 4]]])

In [95]:
# rand

In [96]:
np.random.rand(3,4)

array([[0.29772227, 0.84047164, 0.06366182, 0.7699895 ],
       [0.07167829, 0.31100779, 0.26640355, 0.42620379],
       [0.13220754, 0.36330164, 0.01609233, 0.27791788]])

In [97]:
np.random.rand(6)

array([0.54753492, 0.36738453, 0.46267339, 0.86449401, 0.43159913,
       0.61690447])

In [98]:
np.random.rand(3,2,3)

array([[[0.6351011 , 0.37165196, 0.06181903],
        [0.06175461, 0.49086955, 0.03454859]],

       [[0.54985111, 0.17429155, 0.69824253],
        [0.03993817, 0.78605345, 0.865172  ]],

       [[0.26480933, 0.08957087, 0.35610491],
        [0.34132321, 0.29838091, 0.30436475]]])

In [100]:
# randn

In [99]:
np.random.randn(3,2)

array([[ 0.81936314, -0.55633615],
       [ 0.47784424,  1.19715673],
       [ 0.55481729,  0.10069762]])

In [ ]:
# zeros

In [101]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
np.zeros((3,4),dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [103]:
# ones

In [104]:
np.ones((3,4),dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [106]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [107]:
# full


In [108]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [109]:
np.full((3,4),2.0)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [110]:
# matrix functions

In [114]:
# identity matrix
# it is a square matrix whose main diagonal is elements are 1 and rest elements are 0

In [115]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.

    The identity array is a square array with ones on
    the main diagonal.

    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.

    Examples
    --------
    >>> np.identity(3)
    array([[1.,  0.,  0.

In [116]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [118]:
# diag

In [119]:
m1 = np.random.randint(1,10,(4,4))

In [120]:
m1

array([[5, 5, 7, 2],
       [5, 8, 4, 9],
       [6, 1, 4, 5],
       [2, 4, 3, 1]])

In [121]:
np.diag(m1,k=1)

array([5, 4, 5])

In [122]:
np.diag(m1,k=-1)

array([5, 1, 3])

In [123]:
np.diag(m1,k=2)

array([7, 9])

In [124]:
np.diag(m1,k=-2)

array([6, 4])

In [125]:
np.diag(m1,k=3)

array([2])

In [126]:
np.diag(m1,k=-3)

array([2])

In [127]:
np.diag(m1,k=4)

array([], dtype=int32)

In [128]:
np.diag(m1,k=-4)

array([], dtype=int32)

In [132]:
m2 = np.random.randint(0,10,(5,))

In [133]:
m2

array([5, 3, 0, 2, 6])

In [135]:
np.diag(m2,k=0)

array([[5, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 6]])

In [136]:
np.diag(m2,k=1)

array([[0, 5, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0]])

In [137]:
np.diag(m2,k=2)

array([[0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [138]:
# Broadcasting

In [139]:
arr1 = np.random.randint(0,9,(5,))

In [140]:
arr1

array([8, 8, 1, 0, 2])

In [141]:
arr2 = np.random.randint(0,9,(5,))

In [143]:
arr2

array([4, 4, 5, 3, 6])

In [144]:
arr1 + arr2

array([12, 12,  6,  3,  8])

In [145]:
arr1 / arr2

array([2.        , 2.        , 0.2       , 0.        , 0.33333333])

In [146]:
arr3 = np.random.randint(0,9,(4,))

In [148]:
arr3

array([0, 8, 3, 1])

In [147]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (5,) (4,) 